# Generated by Django 4.2.7 on 2023-12-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musicialmodel_phone_num'),
        ('album', '0004_alter_albummodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='musician.musicialmodel'),
        ),
    ]
