# Generated by Django 4.2.7 on 2023-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicialmodel',
            name='phone_num',
            field=models.CharField(max_length=12),
        ),
    ]
